Citizen.CreateThread(function()
    AddTextEntry('arteonmarke', "Volkswagen Arteon")
    AddTextEntry('bmwmc', "BMW 800GS")
    AddTextEntry('explorerpol', "Ford Explorer")
    AddTextEntry('exploreramb', "Ford Explorer")
    AddTextEntry('DoggoFord', "Ford Mondeo")
    AddTextEntry('mercedesc25', "Mercedes C250")
    AddTextEntry('passatmarke', "Volkswagen Passat")
    AddTextEntry('politiboat', "Politi Båd")
    AddTextEntry('politiheli', "Politi Helikopter")
    AddTextEntry('heliambulan', "EMS Helikopter")
    AddTextEntry('pradomarked', "Toyota Prado")
    AddTextEntry('pradounmarked', "Toyota Prado")
    AddTextEntry('t6marked', "Volkswagen T6")
    AddTextEntry('t6kta', "Volkswagen T6")
    AddTextEntry('touranmarke', "Volkswagen Touran")
    AddTextEntry('volvov90', "Volvo V90")
    AddTextEntry('yamahamc', "Yamaha FJR1300AE")
    AddTextEntry('emstouareq', "Volkswagen Touareg")
    AddTextEntry('micuambu', "Volvo Micu")
    AddTextEntry('ml63akut', "Mercedes ML63 AMG")
    AddTextEntry('otarisambul', "Mercedes Sprinter")
    AddTextEntry('toyotaskilt', "Toyota Hilux")
    AddTextEntry('volvoxc90am', "Volvo XC90")
    AddTextEntry('vwambulance', "VW Crafter")
    AddTextEntry('sprinterambulance', "Mercedes Sprinter")
end)
