-------------------------------------
------- Created by T1GER#9080 -------
------------------------------------- 

Lang = {
  -- CHAT MESSAGES:
  ['dispatch_name']           = '^5 Dispatch: ',
  ['police_notification1']    = '^0^*Armed^r Grand Theft Auto at ^3%s^0 | ^6^*Make: ^0^*%s | ^6Plate: ^0^*%s | ^6Colors: ^0^*%s ^6on ^0^*%s',
  ['police_notification2']    = '^0Grand Theft Auto at ^3%s^0 | ^6^*Make: ^0^*%s | ^6Plate: ^0^*%s | ^6Colors: ^0^*%s ^6on ^0^*%s',
  ['alarm_central']           = '^5 Alarmcentralen: ',
  ['vehicle_alarm_triggered'] = '^0Dit køretøj [%s] alarm er blevet udløst ^3%s^0',

  -- MENU STRINGS:
  ['button_yes']           	  = 'Ja',
  ['button_no']           	  = 'Nej',
  ['shop_main_title']         = 'Vælg et køretøj',
  ['reg_key_title']           = 'Registrer nøglens pris: DKK%s',
  ['reg_alarm_title']         = 'Aquire Alarm Price: DKK%s',
  ['your_current_keys']       = 'Dine nuværende nøgler',
  ['keys_actions_title']      = 'Nøgle funktioner [%s]',
  ['give_key_menu']           = 'Giv nøgler',
  ['remove_key_menu']         = 'Fjern nøgler',
  ['delete_key_menu']         = 'Slet nøgler',
  ['car_interaction_title']   = 'Køretøj funktioner',
  ['keys_mangement_label']    = 'Nøgler',
  ['veh_windows_label']       = 'Vinduer',
  ['veh_door_label']          = 'Døre',
  ['veh_engine_label']        = 'Motor Til/Fra',
  ['veh_neon_label']          = 'Neon Til/Fra',
  ['insurance_label']         = 'Forsikrede biler',
  ['windows_menu_title']      = 'Vinduer Åbn/Luk',
  ['window_front_r']       		= 'Front Vindue (H)',
  ['window_front_l']       		= 'Front Vindue (V)',
  ['window_rear_r']       		= 'Bagerste Vindue (H)',
  ['window_rear_l']       		= 'Bagerste Vindue (V)',
  ['doors_menu_title']        = 'Åben/Luk dør',
  ['door_hood']      			    = 'Kølerhjelm',
  ['door_trunk']       			  = 'Bagklap',
  ['door_front_l']            = 'Front Dør (V)',
  ['door_front_r']            = 'Front Dør (H)',
  ['door_rear_l']             = 'Bagerste Dør (V)',
  ['door_rear_r']             = 'Bagerste Dør (H)',

  -- NOTIFICATIONS:
  ['check_f8_console']        = 'TJEK F8 KONSOLLEN!!!',
  ['not_enough_money']        = 'Du har ikke penge nok!.',
  ['no_players_nearby']       = 'Ingen spillere i nærheden!.',
  ['no_veh_nearby']           = 'Ingen køretøjer i nærheden!.',
  ['no_owned_vehicles']       = 'Du ejer ingen køretøjer!.',
  ['engine_not_running']      = 'Motoren skal være startet!',
  ['must_be_inside_veh']      = 'Du skal være i et køretøj!',
  ['must_be_driver_of_veh']   = 'Du skal være i føresædet af køretøjet!',
  ['veh_must_be_unlocked']    = 'Køretøjet skal være låst op!.',
  ['no_veh_in_direction']     = 'Ingen køretøjer i den retning!.',
  ['vehicle_locked']          = 'Du låste dit køretøj',
  ['vehicle_unlocked']        = 'Du låste op for dit køretøj',
  ['has_key_false']         	= 'Du har ikke nøglerne til denne bil!',
  ['all_veh_has_keys']        = 'Du har registreret nøgler til alle dine køretøjer!.',
  ['key_reg_accepted']        = 'Du registrerede et nyt sæt nøgler til det valgte køretøj!.',
  ['all_veh_have_alarm']      = 'Du har alarm til alle dine køretøjer!.',
  ['alarm_aquired']           = 'Du tilkoblede en alarm til det valgte køretøj!.',
  ['no_registerd_keys']       = 'You have no registered keys to display',
  ['keys_received1']          = 'Du modtog et sæt nøgler til et køretøj [%s].',
  ['keys_received2']          = 'Du modtog et sæt nøgler til et køretøj [%s] fra %s.',
  ['u_gave_keys']             = 'Du gav et sæt nøgler [%s] til %s',
  ['u_removed_a_key']         = 'Du fjernede et sæt nøgler [%s] fra %s',
  ['u_had_a_key_removed']     = 'Dine nøgler [%s] er blevet fjernet af %s',
  ['target_has_no_key_copy']  = '%s har ikke en kopi af denne nøgle...',
  ['couldnt_find_keys']       = 'Kunne ikke finde nøgler til køretøjet med nummerpladen: %s',
  ['keys_deleted']            = 'Nøgler til %s [%s] er blevet slettet.',
  ['engine_toggled_on']       = 'Du startede køretøjets motor',
  ['engine_toggled_off']      = 'Du slukkede køretøjets motor',
  ['npc_ran_away']      		  = 'NPC\'en stak af med nøglerne',
  ['already_lockpicking']     = 'Du lockpicker allerede et køretøj!',
  ['move_closer_to_lockpick'] = 'Bevæg dig tættere på, for at lockpicke køretøjet.',
  ['first_check_if_locked']   = 'Tjek venligst om køretøjet er låst...',
  ['deny_lockpick_unlocked']  = 'Du kan ikke lockpicke et køretøj som ikke er låst..',
  ['veh_lockpicked_success']  = 'Du lockpickede køretøjet.',
  ['veh_lockpicked_fail']     = 'Du mislykkedes med at lockpicke køretøjet.',
  ['deny_hotwire']            = 'Det er ikke nødvendigt at kortslutte dette køretøj.',
  ['hotwire_the_vehicle']     = 'Kortslut køretøjet for at starte motoren.',
  ['already_hotwiring']       = 'Du kortslutter allerede et køretøj!',
  ['veh_hotwire_success']     = 'Du kortsluttede køretøjet.',
  ['veh_hotwire_fail']        = 'Du mislykkedes med at kortslutte køretøjet.',
  ['already_searching']       = 'Du tjekker allerede et køretøj!',
  ['stop_the_vehicle']        = 'Stop venligst køretøjet først!',
  ['cannot_search_car']       = 'Denne bil er tom, lad det ikke gå dig på!',
  ['cash_found_x']      		  = 'Du fandt DKK%s i kontanter.',
  ['item_found_x']      			= 'Du fandt %sx %s.',

  

  -- DRAW TEXTS:
  ['draw_locksmith']          = '[E] Låsesmed',
  ['draw_alarmshop']          = '[E] Alarm butik',

  -- PROGRESSBARS:
  ['progbar_talking']         = 'TALER /W NPC',
  ['progbar_searching']       = 'TJEKKER',
  ['progbar_hotwiring']       = 'KORTSLUTTER',
  ['progbar_lockpicking']     = 'LOCKPICKER',
  
  -- BLIPS:
  ['blip_locksmith']          = 'Låsesmed',
  ['blip_alarmshop']          = 'Alarm butik',
}
