Config = {}
Config.TrunkVehiclePositions = {
    [`komoda`] = {y = 0.85, z = 0.87}, 
    [`glendale`] = {y = 0.85, z = 1.2},
    [`club`] = {y = 1.2, z = 1.3},
    [`Blista`] = {y = 0.7, z = 0.9},
    [`kanjo`] = {y = 1.2, z = 1.2},
    [`rhapsody`] = {y = 0.9, z = 0.85},
    [`premier`] = {y = 0.9, z = 0.9},
    [`windsor`] = {y = 0.8, z = 0.9},
    [`windsor2`] = {y = 0.7, z = 0.9},
    [`brioso2`] = {y = 1.5, z = 1.1},
    [`intruder`] = {y = 0.8, z = 0,85},
    [`felon`] = {y = 0.9, z = 0.9},
    [`felon2`] = {y = 0.7, z = 1.1},
    [`jackal`] = {y = 0.7, z = 0.85},
    [`oracle`] = {y = 0.8, z = 0.85},
    [`oracle2`] = {y = 0.8, z = 0.85},
    [`zion2`] = {y = 0.7, z = 0.9},
    [`stanier`] = {y = 0.9, z = 0.9},
    [`Issi3`] = {y = 1.1, z = 1.1},
    [`gauntlet`] = {y = 0.7, z = 0.8},
    [`gauntlet5`] = {y = 1.4, z = 0.9},
    [`gauntlet4`] = {y = 1.3, z = 0.8},
    [`impaler`] = {y = 2.4, z = 0.9},
    [`Sabregt`] = {y = 1.3, z = 0.8},
    [`voodoo`] = {y = 2.25, z = 0.9},
    [`Dukes`] = {y = 1.2, z = 0.8},
    [`blade`] = {y = 1.3, z = 1},
    [`dominator`] = {y = 0.9, z = 0.8},
    [`dominator8`] = {y = 0.7, z = 0.8},
    [`ellie`] = {y = 0.7, z = 0.8},
    [`slamvan`] = {y = 1.7, z = 1.1},
    [`faction`] = {y = 1, z = 0.8},
    [`Kamacho`] = {y = 1.7, z = 1.1},
    [`mesa3`] = {y = 1.2, z = 1.3},
    [`bobcatxl`] = {y = 2.1, z = 1},
    [`caracara2`] = {y = 1.9, z = 1.3},
    [`Riata`] = {y = 1.9, z = 1.1},
    [`sandking`] = {y = 2.5, z = 1},
    [`stretch`] = {y = 0.9, z = 0.9},
    [`Schafter3`] = {y = 0.9, z = 0.9},
    [`superd`] = {y = 0.8, z = 1.05},
    [`kuruma`] = {y = 1, z = 0.9},
    [`tailgater`] = {y = 0.8, z = 0.9},
    [`alpha`] = {y = 0.8, z = 0.8},
    [`vstr`] = {y = 0.9, z = 0.8},
    [`elegy`] = {y = 0.9, z = 0.9},
    [`euros`] = {y = 1.3, z = 0.6},
    [`Blista2`] = {y = 1.4, z = 0.9},
    [`feltzer2`] = {y = 1.2, z = 0.8},
    [`schlagen`] = {y = 0.9, z = 0.9},
    [`schwarzer`] = {y = 0.7, z = 0.75},
    [`banshee`] = {y = 0.8, z = 0.85},
    [`buffalo`] = {y = 0.8, z = 0.8},
    [`raiden`] = {y = 0.8, z = 0.8},
    [`jester3`] = {y = 1.6, z = 0.9},
    [`sugoi`] = {y = 1, z = 1},
    [`Paragon`] = {y = 0.9, z = 0.9},
    [`carbonizzare`] = {y = 1.2, z = 0.7},
    [`calico`] = {y = 0.8, z = 0.9},
    [`futo`] = {y = 0.9, z = 0.9},
    [`futo2`] = {y = 1.9, z = 1.3},
    [`sultan3`] = {y = 1.7, z = 1},
    [`drafter`] = {y = 0.9, z = 0.9},
    [`tailgater2`] = {y = 0.9, z = 0.9},
    [`jugular`] = {y = 0.8, z = 0.8},
    [`sultan`] = {y = 0.9, z = 0.9},
    [`cypher`] = {y = 0.9, z = 0.8},
    [`Sentinel3`] = {y = 0.9, z = 1.2},
    [`feltzer3`] = {y = 1, z = 0.9},
    [`RapidGT3`] = {y = 0.85, z = 0.8},
    [`Stinger`] = {y = 1, z = 0.8},
    [`michelli`] = {y = 0.8, z = 1.2},
    [`casco`] = {y = 0.75, z = 0.9},
    [`Mamba`] = {y = 0.7, z = 0.87},
    [`Cavalcade`] = {y = 1.4, z = 1.2},
    [`dubsta`] = {y = 1.2, z = 1.2},
    [`dubsta2`] = {y = 1.2, z = 1.2},
    [`serrano`] = {y = 1.2, z = 1},
    [`streiter`] = {y = 1, z = 1},
    [`XLS`] = {y = 1.2, z = 1},
    [`Seminole2`] = {y = 0.95, z = 1.05},
    [`granger`] = {y = 1.6, z = 1.1},
    [`landstalker2`] = {y = 1.2, z = 1.2},
    [`huntley`] = {y = 0.9, z = 0.8},
    [`baller2`] = {y = 1, z = 0.9},
    [`Baller4`] = {y = 1.1, z = 0.9},
    [`novak`] = {y = 1, z = 1.35},
    [`Patriot`] = {y = 0.9, z = 1.2},
    [`Rocoto`] = {y = 1.1, z = 1.1},
    [`rebla`] = {y = 1.1, z = 1.1},
    [`contender`] = {y = 1.6, z = 1.1},
    [`surfer`] = {y = 1.5, z = 1.2},
    [`argento`] = {y = 0.9, z = 1.05},
    [`elegy2`] = {y = 0.8, z = 0.8},
    [`fusilade`] = {y = 0.9, z = 0.85},
    [`penumbra`] = {y = 0.8, z = 0.8},
    [`khamelion`] = {y = 1.0, z = 0.8},
    [`massacro`] = {y = 0.7, z = 0.8},
    [`bestiagts`] = {y = 1.55, z = 0.8},
    [`pariah`] = {y = 1.4, z = 0.675},
    [`italigto`] = {y = 1.0, z = 0.75},
    [`penumbra2`] = {y = 1.4, z = 0.9},
    [`vectre`] = {y = 0.8, z = 0.85},
    [`dilettante`] = {y = 0.8, z = 1.0},
    [`dilettante2`] = {y = 0.8, z = 1.0},
    [`asbo`] = {y = 0.8, z = 1.0},
    [`weevil`] = {y = 1.7, z = 1.1},
    [`sentinel`] = {y = 0.8, z = 0.8},
    [`zion`] = {y = 0.8, z = 0.8},
    [`previon`] = {y = 1.0, z = 0.9},
    [`guardian`] = {y = 1.4, z = 1.3},
    [`prairie`] = {y = 0.8, z = 1.0},
    [`asea`] = {y = 0.8, z = 0.85},
    [`asterope`] = {y = 0.6, z = 0.9},
    [`emperor`] = {y = 0.9, z = 0.9},
    [`fugitive`] = {y = 0.8, z = 0.8},
    [`ingot`] = {y = 0.9, z = 0.9},
    [`regina`] = {y = 0.8, z = 1.2},
    [`romero`] = {y = 1.7, z = 1.0},
    [`stratum`] = {y = 0.8, z = 1.0},
    [`surge`] = {y = 0.8, z = 0.8},
    [`washington`] = {y = 0.8, z = 0.9},
    [`warrener`] = {y = 1.1, z = 0.95},
    [`taxi`] = {y = 0.8, z = 1.5},
    [`primo`] = {y = 0.8, z = 0.9},
    [`cognoscenti`] = {y = 0.9, z = 0.95},
    [`cog55`] = {y = 0.9, z = 0.95},
    [`glendale2`] = {y = 0.85, z = 1.2},
    [`warrener2`] = {y = 2.0, z = 0.9},
    [`manana`] = {y = 1.0, z = 0.9},
    [`peyote`] = {y = 1.0, z = 1.05},
    [`tornado`] = {y = 0.8, z = 0.9},
    [`tornado2`] = {y = 0.8, z = 0.9},
    [`tornado3`] = {y = 0.8, z = 0.9},
    [`pigalle`] = {y = 1.1, z = 0.95},
    [`tornado5`] = {y = 1.1, z = 0.9},
    [`tornado6`] = {y = 0.8, z = 0.82},
    [`cheetah2`] = {y = 4.0, z = 0.85},
    [`fagaloa`] = {y = 1.4, z = 1.1},
    [`neebula`] = {y = 0.8, z = 1.2},
    [`gt500`] = {y = 0.8, z = 0.8},
    [`dynasty`] = {y = 0.8, z = 1.6},
    [`retinue2`] = {y = 1.0, z = 0.95},
    [`sultanrs`] = {y = 0.8, z = 0.95},
    [`baller`] = {y = 0.8, z = 1.1},
    [`bjxl`] = {y = 0.8, z = 1.0},
    [`cavalcade2`] = {y = 1.2, z = 1.0},
    [`fq2`] = {y = 1.0, z = 1.0},
    [`gresley`] = {y = 1.0, z = 1.0},
    [`habanero`] = {y = 1.0, z = 1.0},
    [`landstalker`] = {y = 1.0, z = 1.1},
    [`mesa`] = {y = 0.9, z = 1.0},
    [`radi`] = {y = 1.0, z = 1.0},
    [`seminole`] = {y = 1.0, z = 0.9},
    [`baller3`] = {y = 1.0, z = 0.9},
    [`patriot2`] = {y = 1.0, z = 1.1},
    [`rt3000`] = {y = 0.8, z = 0.8},
    [`remus`] = {y = 1.4, z = 1.3},
    [`dominator7`] = {y = 0.8, z = 0.8},
    [`sadler`] = {y = 1.4, z = 1.3},
    [`minivan`] = {y = 1.0, z = 1.1},
    [`rancherxl`] = {y = 1.0, z = 1.0},
    [`rebel`] = {y = 1.2, z = 1.2},
    [`rebel2`] = {y = 1.2, z = 1.2},
    [`sandking`] = {y = 2.5, z = 1.0},
    [`tornado4`] = {y = 0.8, z = 0.9},
    [`kalahari`] = {y = 1.4, z = 1.0},
    [`brawler`] = {y = 1.1, z = 1.1},
    [`freecrawler`] = {y = 1.0, z = 1.0},
    [`yosemite`] = {y = 1.0, z = 1.0},
    [`hellion`] = {y = 1.0, z = 1.3},
    [`everon`] = {y = 0.9, z = 1.0},
    [`buffaloh`] = {y = 0.8, z = 0.8},
    [`cypherct`] = {y = 0.8, z = 0.8},
    [`dubsta4x4`] = {y = 1.0, z = 1.2},
    [`dubsta22`] = {y = 1.0, z = 1.3},
    [`elegyx`] = {y = 0.8, z = 0.8},
    [`gresleyh`] = {y = 1.0, z = 1.0},
    [`komodafr`] = {y = 0.8, z = 0.85},
    [`oracxsle`] = {y = 0.8, z = 0.85},
    [`paragonxr`] = {y = 0.8, z = 0.85},
    [`stratumc`] = {y = 0.8, z = 0.8},
    [`streiter2`] = {y = 0.8, z = 0.9},
}

Config.Animations = {
    {
        label = 'Gangart',
        items = {
            {name = "casual", label = "Afslappet #1"},
            {name = "casual2", label = "Afslappet #2"},
            {name = "casual3", label = "Afslappet #3"},
            {name = "casual4", label = "Afslappet #4"},
            {name = "casual5", label = "Afslappet #5"},
            {name = "casual6", label = "Afslappet #6"},
            {name = "alien", label = "Alien"},
            {name = "armored", label = "Armored"},
            {name = "arrogant", label = "Arrogant"},
            {name = "scared", label = "Bange"},
            {name = "cop", label = "Betjent #1"},
            {name = "cop2", label = "Betjent #2"},
            {name = "cop3", label = "Betjent #3"},
            {name = "chichi", label = "Chi Chi"},
            {name = "femme", label = "Femme"},
            {name = "flee", label = "Flygter"},
            {name = "franklin", label = "Franklin"},
            {name = "sassy", label = "Fræk #1"},
            {name = "sassy2", label = "Fræk #2"},
            {name = "drunk", label = "Fuld #1"},
            {name = "drunk2", label = "Fuld #2"},
            {name = "drunk3", label = "Fuld #3"},
            {name = "drunk4", label = "Fuld #4"},
            {name = "gangster", label = "Gangster #1"},
            {name = "gangster2", label = "Gangster #2"},
            {name = "gangster3", label = "Gangster #3"},
            {name = "gangster4", label = "Gangster #4"},
            {name = "gangster5", label = "Gangster #5"},
            {name = "grooving", label = "Grooving"},
            {name = "hipster", label = "Hipster"},
            {name = "hobo", label = "Hjemløs"},
            {name = "quick", label = "Hurtig"},
            {name = "heels", label = "Høje Hæle #1"},
            {name = "heels2", label = "Høje Hæle #2"},
            {name = "tough2", label = "Hård Type"},
            {name = "handcuffs", label = "I håndjern"},
            {name = "fire", label = "Ild #1"},
            {name = "fire2", label = "Ild #2"},
            {name = "fire3", label = "Ild #3"},
            {name = "jog", label = "Jogging"},
            {name = "sad", label = "Ked af det"},
            {name = "slow", label = "Langsom"},
            {name = "lemar", label = "Lemar"},
            {name = "lester", label = "Lester #1"},
            {name = "lester2", label = "Lester #2"},
            {name = "shady", label = "Lyssky"},
            {name = "runner", label = "Løber"},
            {name = "maneater", label = "Maneater"},
            {name = "michael", label = "Michael"},
            {name = "brave", label = "Modig"},
            {name = "muscle", label = "Muskler"},
            {name = "confident", label = "Selvsikker"},
            {name = "janitor", label = "Pedel #1"},
            {name = "janitor2", label = "Pedel #2"},
            {name = "posh", label = "Posh #1"},
            {name = "posh2", label = "Posh #2"},
            {name = "money", label = "Rig"},
            {name = "sexy", label = "Sexy"},
            {name = "trash", label = "Skraldemand #1"},
            {name = "trash2", label = "Skraldemand #2"},
            {name = "hurry", label = "Skynde sig"},
            {name = "sough", label = "Sug"},
            {name = "swagger", label = "Swagger"},
            {name = "trevor", label = "Trevor"},
            {name = "wide", label = "Tyk"},
            {name = "guard", label = "Vagt"},
            {name = "hiking", label = "Vandretur 1"},
            {name = "reset", label = "Reset"},
        }
    },
    {
        label = 'Humør',
        items = {
            {name = "angry", label = "Sur"},
            {name = "drunk", label = "Fuld"},
            {name = "dumb", label = "Dum"},
            {name = "electrocuted", label = "I stødet"},
            {name = "grumpy", label = "Knaven #1"},
            {name = "grumpy2", label = "Knaven #2"},
            {name = "grumpy3", label = "Knaven #3"},
            {name = "happy", label = "Glad"},
            {name = "injured", label = "Skadet"},
            {name = "joyful", label = "Fjollet"},
            {name = "mouthbreather", label = "Træk vejret gennem munden"},
            {name = "never_blink", label = "Blink Aldrig"},
            {name = "one_eye", label = "Et øjet"},
            {name = "shocked", label = "Chokeret #1"},
            {name = "shocked2", label = "Chokeret #2"},
            {name = "sleeping", label = "Søvning #1"},
            {name = "sleeping2", label = "Søvning #2"},
            {name = "sleeping3", label = "Søvning #3"},
            {name = "smug", label = "Selvglad"},
            {name = "speculative", label = "Spekulative"},
            {name = "stressed", label = "Stresset"},
            {name = "sulking", label = "Surmulende"},
            {name = "weird", label = "Mærkelig #1"},
            {name = "weird2", label = "Mærkelig #2"},
            {name = "reset", label = "Reset"},
        }
    },
    {
        label = 'Job Relateret Animationer',
        items = {
            {name = "cop", label = "Betjent #1"},
            {name = "cop2", label = "Betjent #2"},
            {name = "cop3", label = "Betjent #3"},
            {name = "copbeacon", label = "Betjent #4"},
            {name = "reaching", label = "Betjent #5"},
            {name = "inspect", label = "Inspicere"},
            {name = "mechanic", label = "Mekaniker #1"},
            {name = "mechanic2", label = "Mekaniker #2"},
            {name = "mechanic3", label = "Mekaniker #3"},
            {name = "mechanic4", label = "Mekaniker #4"},
            {name = "medic", label = "Medic #1"},
            {name = "medic2", label = "Medic #2"},
            {name = "cpr", label = "CPR #1"},
            {name = "cpr2", label = "CPR #2"},
            {name = "type", label = "Skrive #1"},
            {name = "type2", label = "Skrive #2"},
            {name = "type3", label = "Skrive #3"},
            {name = "type4", label = "Skrive #4"},
            {name = "clown", label = "Klovn #1"},
            {name = "clown2", label = "Klovn #2"},
            {name = "clown3", label = "Klovn #3"},
            {name = "clown4", label = "Klovn #4"},
            {name = "clown5", label = "Klovn #5"},
            {name = "guard", label = "Vagt"},
            {name = "hammer", label = "Hammer"},
            {name = "janitor", label = "Pedel"},
            {name = "push", label = "Skub #1"},
            {name = "push2", label = "Skub #2"},
            {name = "pickup", label = "Samle op"},
            {name = "statue", label = "Statue #1"},
            {name = "statue2", label = "Statue #2"},
            {name = "statue3", label = "Statue #3"},
            {name = "radio", label = "Radio"},
            {name = "Leafblower", label = "Løvblæser"},
            {name = "Maid", label = "Stuepige"},
            {name = "musician", label = "Musiker"},
            {name = "weld", label = "Svejs"},
            {name = "record", label = "Optag"},
            {name = "fising", label = "Fisker"},
            {name = "planter", label = "Planter"},
        }
    },
    {
        label = 'Sport Animationer',
        items = {
            {name = "hiking", label = "Vandretur"},
            {name = "jog", label = "Jogging #1"},
            {name = "jog2", label = "Jogging #2"},
            {name = "jog3", label = "Jogging #3"},
            {name = "jog4", label = "Jogging #4"},
            {name = "jog5", label = "Jogging #5"},
            {name = "jumpingjacks", label = "Sprældemænd"},
            {name = "meditate", label = "Meditere #1"},
            {name = "meditate2", label = "Meditere #2"},
            {name = "meditate3", label = "Meditere #3"},
            {name = "outofbreath", label = "Forpustet"},
            {name = "pushup", label = "Armbøjninger"},
            {name = "situp", label = "Mavebøjninger"},
            {name = "chinup", label = "Armløft"},
            {name = "flip", label = "Baglænder #1"},
            {name = "flip2", label = "Baglænder #2"},
            {name = "golfswing", label = "Golf Sving"},
            {name = "stretch", label = "Stræk ud #1"},
            {name = "stretch2", label = "Stræk ud #2"},
            {name = "stretch3", label = "Stræk ud #3"},
            {name = "stretch4", label = "Stræk ud #4"},
            {name = "flex", label = "Flex Muskler"},
            {name = "karate", label = "Karate 1"},
            {name = "karate2", label = "Karate 2"},
            {name = "boxing", label = "Bokse 1"},
            {name = "boxing2", label = "Bokse 2"},
            {name = "yoga", label = "Yoga"},
            {name = "slugger", label = "Baseball"},
            {name = "clap", label = "Klap"},
            {name = "clapangry", label = "Klap surt"},
            {name = "slowclap", label = "Klap Langsom #1"},
            {name = "slowclap2", label = "Klap Langsom #2"},
            {name = "slowclap3", label = "Klap Langsom #3"},
            {name = "weights", label = "Vægte 1"},
            {name = "weights2", label = "Vægte 2"},
        }
    },
    {
        label = 'Afventende Animationer',
        items = {
            {name = "sunbathe", label = "Solbad #1"},
            {name = "sunbathe2", label = "Solbad #2"},
            {name = "sunbathe3", label = "Solbad #3"},
            {name = "sunbatheback", label = "Solbad #4"},
            {name = "cloudgaze", label = "Se på skyer #1"},
            {name = "cloudgaze2", label = "Se på skyer #2"},
            {name = "chill", label = "chill"},
            {name = "wait", label = "Vent #1"},
            {name = "wait3", label = "Vent #2"},
            {name = "wait4", label = "Vent #3"},
            {name = "wait5", label = "Vent #4"},
            {name = "wait6", label = "Vent #5"},
            {name = "wait7", label = "Vent #6"},
            {name = "wait8", label = "Vent #7"},
            {name = "wait9", label = "Vent #8"},
            {name = "wait10", label = "Vent #9"},
            {name = "wait11", label = "Vent #10"},
            {name = "wait12", label = "Vent #11"},
            {name = "wait13", label = "Vent #12"},
            {name = "idle", label = "Inaktiv #1"},
            {name = "idle2", label = "Inaktiv #2"},
            {name = "idle3", label = "Inaktiv #3"},
            {name = "idle4", label = "Inaktiv #4"},
            {name = "idle5", label = "Inaktiv #5"},
            {name = "idle6", label = "Inaktiv #6"},
            {name = "idle7", label = "Inaktiv #7"},
            {name = "idle8", label = "Inaktiv #8"},
            {name = "idle9", label = "Inaktiv #9"},
            {name = "idle10", label = "Inaktiv #10"},
            {name = "idle11", label = "Inaktiv #11"},
            {name = "idledrunk", label = "Inaktiv Fuld #1"},
            {name = "idledrunk2", label = "Inaktiv Fuld #2"},
            {name = "idledrunk2", label = "Inaktiv Fuld #3"},
        }
    },
    {
        label = 'Sociale Animationer',
        items = {
            {name = "argue", label = "Diskutere #1"},
            {name = "argue2", label = "Diskutere #2"},
            {name = "blowkiss", label = "Luftkys #1"},
            {name = "blowkiss2", label = "Luftkys #2"},
            {name = "comeatmebro", label = "Come At Me Bro"},
            {name = "fightme", label = "Kom an #1"},
            {name = "fightme2", label = "Kom an #2"},
            {name = "finger", label = "Fuck Fingeren #1"},
            {name = "finger2", label = "Fuck Fingeren #2"},
            {name = "flipoff", label = "Fuck Fingeren #3"},
            {name = "flipoff2", label = "Fuck Fingeren #4"},
            {name = "handshake", label = "Giv Hånd #1"},
            {name = "handshake2", label = "Giv Hånd #2"},
            {name = "bringiton", label = "Kom med det"},
            {name = "hug", label = "Kram #1"},
            {name = "hug2", label = "Kram #2"},
            {name = "hug3", label = "Kram #3"},
            {name = "hug4", label = "Kram #4"},
            {name = "no", label = "Nej #1"},
            {name = "no2", label = "Nej #2"},
            {name = "noway", label = "No Way"},
            {name = "ok", label = "OK"},
            {name = "salute", label = "Honnør #1"},
            {name = "salute2", label = "Honnør #2"},
            {name = "salute3", label = "Honnør #3"},
            {name = "screwyou", label = "Screw You"},
            {name = "thumbsup", label = "Thumbs Up #1"},
            {name = "thumbsup2", label = "Thumbs Up #2"},
            {name = "thumbsup3", label = "Thumbs Up #3"},
            {name = "wave", label = "Vinke #1"},
            {name = "wave2", label = "Vinke #2"},
            {name = "wave3", label = "Vinke #3"},
            {name = "wave4", label = "Vinke #4"},
            {name = "wave5", label = "Vinke #5"},
            {name = "wave6", label = "Vinke #6"},
            {name = "wave7", label = "Vinke #7"},
            {name = "wave8", label = "Vinke #8"},
            {name = "wave9", label = "Vinke #9"},
            {name = "namaste", label = "Namaste"},
            {name = "slap", label = "Slå"},
            {name = "headbutt", label = "Giv en skalle"},
            {name = "boi", label = "Boi"},
            {name = "threaten", label = "True"},
            {name = "bow", label = "Buk dig #1"},
            {name = "bow2", label = "Buk dig #2"},
            {name = "punching", label = "Slå i luften"},
            {name = "hangout", label = "Hæng ud"},
            {name = "stickup", label = "Hænderne op"},
            {name = "aim", label = "Pistol animation #1"},
            {name = "aim2", label = "Pistol animation #2"},
            {name = "knucklecrunch", label = "Pas"},
            {name = "cutthroat", label = "True 1"},
            {name = "cutthroat2", label = "True 2"},
            {name = "mindblown", label = "Mindblown 1"},
            {name = "mindblown2", label = "Mindblown 2"},
            {name = "stink", label = "Lugte"},
            {name = "taunt", label = "Håne 1"},
            {name = "taunt2", label = "Håne 2"},
            {name = "taunt3", label = "Håne 3"},
            {name = "taunt4", label = "Håne 4"},
            {name = "taunt5", label = "Håne 5"},
            {name = "taunt6", label = "Håne 6"},
            {name = "taunt7", label = "Håne 7"},
            {name = "adjusttie", label = "Juster slips"},
        }
    },
    {
        label = 'Emotes Med Props #1',
        items = {
            {name = "umbrella", label = "Paraply"},
            {name = "notepad", label = "Tag Noter #1"},
            {name = "notepad2", label = "Tag Noter #2"},
            {name = "clipboard", label = "Udklipsholder #1"},
            {name = "clipboard2", label = "Udklipsholder #2"},
            {name = "book", label = "Bog"},
            {name = "map", label = "Kort"},
            {name = "box", label = "Kasse"},
			{name = "pizza", label = "Pizzabakke"},
            {name = "rose", label = "Rose"},
            {name = "bouquet", label = "Buket"},
            {name = "teddy", label = "Bamse"},
            {name = "backpack", label = "Rygsæk"},
            {name = "suitcase", label = "Kuffert #1"},
            {name = "suitcase2", label = "Kuffert #2"},
            {name = "brief3", label = "Mappe"},
            {name = "smoke", label = "Ryg en Cigaret #1"},
            {name = "smoke2", label = "Ryg en Cigaret #2"},
            {name = "smoke3", label = "Ryg en Cigaret #3"},
            {name = "smoke4", label = "Ryg en Cigaret #4"},
            {name = "cig", label = "Ryg en Cigaret #5"},
            {name = "cigar", label = "Ryg en Cigar #1"},
            {name = "cigar2", label = "Ryg en Cigar #2"},
            {name = "joint", label = "Ryg en Joint #1"},
            {name = "joint2", label = "Ryg en Joint #2"},
            {name = "smokeweed", label = "Ryg Hash"},
            {name = "bong", label = "Ryg en Bong"},
            {name = "newscam", label = "Nyhedskamera"},
            {name = "newsmic", label = "Nyhedsmikrofon"},
            {name = "microphone", label = "Mikrofon"},
            {name = "newsbmic", label = "Nyheds?"},
            {name = "toolbox", label = "Værktøjskasse 1"},
            {name = "toolbox2", label = "Værktøjskasse 2"},
            {name = "binoculars", label = "Kiggert 1"},
            {name = "binoculars2", label = "Kiggert 2"},
            {name = "binoculars3", label = "Kiggert 3"},
            {name = "fuel", label = "Benzin 1"},
            {name = "fuelcarry", label = "Benzin 2"},
            {name = "shopping", label = "Shopping poser 1"},
            {name = "shopping2", label = "Shopping poser 2"},
        }
    },
    {
        label = 'Emotes Med Props #2',
        items = {
            {name = "beg", label = "Tig"},
            {name = "makeitrain", label = "Make It Rain"},
            {name = "tablet", label = "Tablet #1"},
            {name = "tablet2", label = "Tablet #2"},
            {name = "camera", label = "Kamera"},
            {name = "phonecall", label = "Telefon Opkald"},
            {name = "phone", label = "Telefon"},
            {name = "clean", label = "Gør rent #1"},
            {name = "clean2", label = "Gør rent #2"},
        }
    },
    {
        label = 'Mad og Drikkevare',
        items = {
            {name = "coffee", label = "Kaffe"},
            {name = "whiskey", label = "Whiskey"},
            {name = "beer", label = "Øl"},
            {name = "wine", label = "Vin"},
            {name = "champagne", label = "Champagne"},
            {name = "champagnespray", label = "Champagnespray"},
            {name = "soda", label = "Sodavand"},
            {name = "donut", label = "Donut"},
            {name = "burger", label = "Burger"},
            {name = "sandwich", label = "Sandwich"},
            {name = "egobar", label = "Egobar"},
            {name = "cup", label = "Random Kop"},
            {name = "drink", label = "Drik"},
            {name = "eat", label = "Spis"},
            {name = "bbq", label = "BBQ"},
            {name = "flute", label = "Vin glas"},
            {name = "carryfoodbag", label = "Bær madpose #1"},
            {name = "carryfoodbag2", label = "Bær madpose #2"},
            {name = "carryfoodbag3", label = "Bær madpose #3"},
            {name = "carryfoodtray", label = "Bær madbakke 1"},
            {name = "carryfoodtray2", label = "Bær madbakke 2"},
            {name = "carryfoodtray3", label = "Bær madbakke 3"},
            {name = "carryfoodtray4", label = "Bær madbakke 4"},
            {name = "carryfoodtray5", label = "Bær madbakke 5"},
            {name = "carryfoodtray6", label = "Bær madbakke 6"},
            {name = "carryfoodtray7", label = "Bær madbakke 7"},
            {name = "carryfoodtray8", label = "Bær madbakke 8"},
            {name = "carryfoodtray9", label = "Bær madbakke 9"},
        }
    },
    {
        label = 'Musikinstrumenter Animationer',
        items = {
            {name = "airsynth", label = "Airsynth"},
            {name = "airguitar", label = "Luft Guitar"},
            {name = "guitar", label = "Guitar #1"},
            {name = "guitar2", label = "Guitar #2"},
            {name = "guitarelectric", label = "Guitar Elektrisk #1"},
            {name = "guitarelectric2", label = "Guitar Elektrisk #2"},
        }
    },
    {
        label = 'Sidde Animationer',
        items = {
            {name = "sitsad", label = "Sid ned ked af det"},
            {name = "sitdrunk", label = "Sid ned fuld"},
            {name = "sitscared", label = "Sid ned bange #1"},
            {name = "sitscared2", label = "Sid ned bange #2"},
            {name = "sitscared3", label = "Sid ned bange #3"},
            {name = "sit", label = "Sid ned på jorden #1"},
            {name = "sit2", label = "Sid ned på jorden #2"},
            {name = "sit3", label = "Sid ned på jorden #3"},
            {name = "sit4", label = "Sid ned på jorden #4"},
            {name = "sit5", label = "Sid ned på jorden #5"},
            {name = "sit6", label = "Sid ned på jorden #6"},
            {name = "sit7", label = "Sid ned på jorden #7"},
            {name = "sit8", label = "Sid ned på jorden #8"},
            {name = "sit9", label = "Sid ned på jorden #9"},
            {name = "sitlean", label = "Sid ned #10"},
            {name = "sitchair", label = "Sid ned i stolen #1"},
            {name = "sitchair2", label = "Sid ned i stolen #2"},
            {name = "sitchair3", label = "Sid ned i stolen #3"},
            {name = "sitchair4", label = "Sid ned i stolen #4"},
            {name = "sitchair5", label = "Sid ned i stolen #5"},
            {name = "sitchair6", label = "Sid ned i stolen #6"},
            {name = "sitchairside", label = "Sid ned i stolen #7"},
        }
    },
    {
        label = 'Fortnite danse',
        items = {
            {name = "crossbounce", label = "Cross bounce"},
            {name = "dontstart", label = "Dont Start"},
            {name = "orangejustice", label = "Orange Justice"},
            {name = "renegade", label = "Renegade"},
            {name = "rickroll", label = "Rick Roll"},
            {name = "savage", label = "Savage"},
            {name = "sayso", label = "Say So"},
            {name = "takel", label = "Take the L"},
            {name = "slide", label = "Tootsie Slide"},
            {name = "dbdance1", label = "Mdance"},
            {name = "dbdance2", label = "A1 Dance"},
            {name = "dbdance3", label = "Boogie Down"},
            {name = "dbdance4", label = "Break Boy"},
            {name = "dbdance5", label = "Breakfast Coffee Dance"},
            {name = "dbdance6", label = "Candy Dance"},
            {name = "dbdance7", label = "Cheerleader Dance"},
            {name = "dbdance8", label = "Crab Dance"},
            {name = "dbdance9", label = "Eastern Blocc"},
            {name = "dbdance10", label = "Electro Swing"},
            {name = "dbdance11", label = "Electro Shuffle 1"},
            {name = "electroshuffle", label = "Electro Shuffle 2"},
            {name = "electroshuffle2", label = "Electro Shuffle 3"},
            {name = "dbdance12", label = "Floss"},
            {name = "dbdance13", label = "Grooving Jam"},
            {name = "dbdance14", label = "Hillbilly Shuffle"},
            {name = "dbdance15", label = "Laser Dance"},
            {name = "dbdance16", label = "Ribbon Dance"},
            {name = "dbdance17", label = "Running Man"},
            {name = "dbdance18", label = "Step Breakdance"},
            {name = "dbdance19", label = "Cowboy Dance"},
            {name = "dbdance20", label = "Egyptian Dance"},
            {name = "dbdance21", label = "Swipe It"},
            {name = "clock", label = "Around the clock"},
            {name = "dancemoves", label = "Dance moves"},
            {name = "discodance", label = "Disco Dance"},
            {name = "fresh", label = "Fresh"},
            {name = "gylphic", label = "Glyphic"},
            {name = "hitit", label = "Hit It"},
            {name = "robotdance", label = "Robot Dance"},
            {name = "frightfunk", label = "Fright Funk"},
            {name = "gloss", label = "Gloss"},
            {name = "lastforever", label = "Last Forever"},
            {name = "smoothmoves", label = "Smooth moves"},
            {name = "introducing", label = "Introducing..."},
        }
    },
    {
        label = 'Diverse Animationer #1',
        items = {
            {name = "mugshot", label = "Mugshot"},
            {name = "beast", label = "Dyr"},
            {name = "prone", label = "Læg dig på jorden"},
            {name = "pullover", label = "Kør ind til siden"},
            {name = "bartender", label = "Bartender"},
            {name = "curtsy", label = "Skør"},
            {name = "me", label = "Mig?"},
            {name = "metal", label = "Metal"},
            {name = "nosepick", label = "Pil næse"},
            {name = "countdown", label = "Tæl ned"},
            {name = "shakeoff", label = "Fjern snavs"},
            {name = "shot", label = "Skudt"},
            {name = "sleep", label = "Sov"},
            {name = "stumble", label = "Snuble"},
            {name = "smell", label = "Lugt"},
            {name = "warmth", label = "Varm dig"},
            {name = "yeah", label = "Yeah!"},
            {name = "lift", label = "Kan jeg få et lift?"},
            {name = "petting", label = "Kæl med dyr"},
            {name = "crawl", label = "Kravl"},
            {name = "ledge", label = "Stå ved klippeafsats"},
            {name = "airplane", label = "Flyvemaskine"},
            {name = "peek", label = "Kig rundt om hjørnet"},
            {name = "cough", label = "Host"},
            {name = "celebrate", label = "Fejre"},
            {name = "cheer", label = "Jubel"},
            {name = "handsup", label = "Tag hænderne op"},
            {name = "adjust", label = "Ret på tøjet"},
            {name = "pull", label = "Træk"},
            {name = "pee", label = "Tis"},
            {name = "puddle", label = "Vandpyt"},
            {name = "texting", label = "Skriv på din telefon"},
            {name = "lookout", label = "Hold udkig"},
            {name = "impatient", label = "Være utålmodig"},
            {name = "wank", label = "Fab!"},
            {name = "itchy", label = "Klø kuglerne!"},
        }
    },
    {
        label = 'Diverse Animationer #2',
        items = {
            {name = "point", label = "Peg"},
            {name = "pointdown", label = "Peg nedaf"},
            {name = "pointright", label = "Peg til højre"},
            {name = "crossarms", label = "Kryds dine arme #1"},
            {name = "crossarms2", label = "Kryds dine arme #2"},
            {name = "crossarms3", label = "Kryds dine arme #3"},
            {name = "crossarms4", label = "Kryds dine arme #4"},
            {name = "crossarms5", label = "Kryds dine arme #5"},
            {name = "crossarms6", label = "Kryds dine arme #6"},
            {name = "crossarmsside", label = "Kryds dine arme #7"},
            {name = "foldarms", label = "Fold dine arme #1"},
            {name = "foldarms2", label = "Fold dine arme #2"},
            {name = "facepalm", label = "Facepalm #1"},
            {name = "facepalm2", label = "Facepalm #2"},
            {name = "facepalm3", label = "Facepalm #3"},
            {name = "facepalm4", label = "Facepalm #4"},
            {name = "fallover", label = "Fald #1"},
            {name = "fallover2", label = "Fald #2"},
            {name = "fallover3", label = "Fald #3"},
            {name = "fallover4", label = "Fald #4"},
            {name = "fallover5", label = "Fald #5"},
            {name = "fallasleep", label = "Fald i søvn"},
            {name = "die", label = "Spil død"},
            {name = "kneel", label = "Knæl #1"},
            {name = "kneel2", label = "Knæl #2"},
            {name = "kneel3", label = "Knæl #3"},
            {name = "knock", label = "Bank på dør #1"},
            {name = "knock2", label = "Bank på dør #2"},
            {name = "damn", label = "Damn #1"},
            {name = "damn2", label = "Damn #2"},
            {name = "scared", label = "Bange #1"},
            {name = "scared2", label = "Bange #2"},
            {name = "gangsign", label = "Bande Tegn #1"},
            {name = "gangsign2", label = "Bande Tegn #2"},
            {name = "superhero", label = "Superhelt #1"},
            {name = "superhero2", label = "Superhelt #2"},
            {name = "slide", label = "Glid på knæende #1"},
            {name = "slide2", label = "Glid på knæende #2"},
            {name = "slide3", label = "Glid på knæende #3"},
        }
    },
    {
        label = 'Diverse Animationer #3',
        items = {
            {name = "peace", label = "Peace #1"},
            {name = "peace2", label = "Peace #2"},
            {name = "lol", label = "LOL #1"},
            {name = "lol2", label = "LOL #2"},
            {name = "whistle", label = "Fløjt #1"},
            {name = "whistle2", label = "Fløjt #2"},
            {name = "t", label = "Stå i et T #1"},
            {name = "t2", label = "Stå i et T #2"},
            {name = "mindcontrol", label = "Tanke Kontrol #1"},
            {name = "mindcontrol2", label = "Tanke Kontrol #2"},
            {name = "nervous", label = "Nervøs #1"},
            {name = "nervous2", label = "Nervøs #2"},
            {name = "nervous3", label = "Nervøs #3"},
            {name = "think", label = "Tænk #1"},
            {name = "think2", label = "Tænk #2"},
            {name = "think3", label = "Tænk #3"},
            {name = "think4", label = "Tænk #4"},
            {name = "shrug", label = "Træk på skulderen #1"},
            {name = "shrug2", label = "Træk på skulderen #2"},
            {name = "passout", label = "Besvim #1"},
            {name = "passout2", label = "Besvim #2"},
            {name = "passout3", label = "Besvim #3"},
            {name = "passout4", label = "Besvim #4"},
            {name = "passout5", label = "Besvim #5"},
            {name = "leanflirt", label = "Læn dig flirtende"},
            {name = "leanhigh", label = "Læn dig højt #1"},
            {name = "leanhigh2", label = "Læn dig højt #2"},
            {name = "lean", label = "Læn dig op af mur #1"},
            {name = "lean2", label = "Læn dig op af mur #2"},
            {name = "lean3", label = "Læn dig op af mur #3"},
            {name = "lean4", label = "Læn dig op af mur #4"},
            {name = "lean5", label = "Læn dig op af mur #5"},
            {name = "leanbar", label = "Læn dig op af baren #1"},
            {name = "leanbar2", label = "Læn dig op af baren #2"},
            {name = "leanbar3", label = "Læn dig op af baren #3"},
            {name = "leanbar4", label = "Læn dig op af baren #4"},
            {name = "leanside", label = "Læn dig til siden #1"},
            {name = "leanside2", label = "Læn dig til siden #2"},
            {name = "leanside3", label = "Læn dig til siden #3"},
            {name = "leanside4", label = "Læn dig til siden #4"},
            {name = "leanside5", label = "Læn dig til siden #5"},
        }
    },
    {
        label = 'Diverse Animationer #4',
        items = {
            {name = "gesture_doublepoint", label = "Come At Me"},
            {name = "gesture_dramaticpoint", label = "Dramatisk peg"},
            {name = "gesture_flex", label = "Flex"},
            {name = "gesture_icant", label = "Fald tilbage"},
            {name = "gesture_loser", label = "Loser"},
            {name = "gesture_salute", label = "YES SIR"},
            {name = "gesture_taunt", label = "Skær halsen over"},
            {name = "gesture_victory", label = "Vinder jubel"},
            {name = "gesture_wave", label = "Vink"},
            {name = "heart", label = "Heart"},
            {name = "badmood", label = "Bad mood"},
            {name = "bunnyhop", label = "Bunnyhop"},
            {name = "burpee", label = "Burpee"},
            {name = "callme", label = "Call Me"},
            {name = "coronet", label = "Coronet"},
            {name = "dcry", label = "Cry"},
            {name = "hailcab", label = "Hailcab"},
            {name = "kepler", label = "King Of The Jungle"},
            {name = "mindblown", label = "Mindblown"},
            {name = "uproar", label = "Uproar"},
            {name = "yeet", label = "Yeet"},
            {name = "mgangsigns_1", label = "Gangsign 1"},
            {name = "mgangsigns_2", label = "Gangsign 2"},
            {name = "mgangsigns_3", label = "Gangsign 3"},
            {name = "mgangsigns_4", label = "Gangsign 4"},
            {name = "mgangsigns_5", label = "Gangsign 5"},
            {name = "mgangsigns_6", label = "Gangsign 6"},
            {name = "mgangsigns_7", label = "Gangsign 7"},
            {name = "mgangsigns_8", label = "Gangsign 8"},
            {name = "mgangsigns_9", label = "Gangsign 9"},
            {name = "haenderpaaryg", label = "Hænder på ryg"},
            {name = "sidafslappende", label = "Sid afslappende"},
            {name = "holdvest1", label = "Hold vest 1"},
            {name = "holdvest2", label = "Hold vest 2"},
            {name = "gaapaaknae", label = "Gå på knæ"},
        }
    },
    {
        label = 'Skilte',
        items = {
            {name = "ssign", label = "Skilt #1"},
            {name = "ssign2", label = "Skilt #2"},
            {name = "ssign3", label = "Skilt #3"},
            {name = "ssign4", label = "Skilt #4"},
            {name = "ssign5", label = "Skilt #5"},
            {name = "ssign6", label = "Skilt #6"},
            {name = "ssign7", label = "Skilt #7"},
            {name = "ssign8", label = "Skilt #8"},
            {name = "ssign9", label = "Skilt #9"},
        }
    },
    {
        label = 'Danse Emotes #1',
        items = {
            {name = "dance", label = "Dans #1"},
            {name = "dance2", label = "Dans #2"},
            {name = "dance3", label = "Dans #3"},
            {name = "dance4", label = "Dans #4"},
            {name = "dance6", label = "Dans #5"},
            {name = "dance7", label = "Dans #6"},
            {name = "dance8", label = "Dans #7"},
            {name = "dance9", label = "Dans #8"},
            {name = "dance18", label = "Dans #9"},
            {name = "dance19", label = "Dans #10"},
            {name = "danceupper", label = "Dans Øvre #1"},
            {name = "danceupper2", label = "Dans Øvre #2"},
            {name = "danceglowstick", label = "Dans med Knæklys #1"},
            {name = "danceglowstick2", label = "Dans med Knæklys #2"},
            {name = "danceglowstick3", label = "Dans med Knæklys #3"},
            {name = "dancehorse", label = "Dans som en Hest #1"},
            {name = "dancehorse2", label = "Dans som en Hest #2"},
            {name = "dancehorse3", label = "Dans som en Hest #3"},
            {name = "fishdance", label = "Fiske Dans"},
            {name = "jazzhands", label = "Jazz Hænder"},
            {name = "lapdance", label = "Lapdance #1"},
            {name = "lapdance2", label = "Lapdance #2"},
            {name = "lapdance3", label = "Lapdance #3"},
            {name = "lapdance4", label = "Lapdance #4"},
            {name = "twerk", label = "Twerk"},
        }
    },
    {
        label = 'Danse Emotes #2',
        items = {
            {name = "dancef", label = "Dans F #1"},
            {name = "dancef2", label = "Dans F #2"},
            {name = "dancef3", label = "Dans F #3"},
            {name = "dancef4", label = "Dans F #4"},
            {name = "dancef5", label = "Dans F #5"},
            {name = "dancef6", label = "Dans F #6"},
            {name = "danceslow", label = "Dans Langsomt #1"},
            {name = "danceslow2", label = "Dans Langsomt #2"},
            {name = "danceslow3", label = "Dans Langsomt #3"},
            {name = "danceslow4", label = "Dans Langsomt #4"},
            {name = "danceshy", label = "Dans Genert #1"},
            {name = "danceshy2", label = "Dans Genert #2"},
            {name = "dancesilly", label = "Dans Fjolet #1"},
            {name = "dancesilly2", label = "Dans Fjolet #2"},
            {name = "dancesilly3", label = "Dans Fjolet #3"},
            {name = "dancesilly4", label = "Dans Fjolet #4"},
            {name = "dancesilly5", label = "Dans Fjolet #5"},
            {name = "dancesilly6", label = "Dans Fjolet #6"},
            {name = "dancesilly7", label = "Dans Fjolet #7"},
            {name = "dancesilly8", label = "Dans Fjolet #8"},
            {name = "dancesilly9", label = "Dans Fjolet #9"},
        }
    },
    {
        label = 'Danse Emotes #3',
        items = {
            {name = "ddance1", label = "Custom Dans 1"},
            {name = "ddance2", label = "Custom Dans 2"},
            {name = "ddance3", label = "Custom Dans 3"},
            {name = "ddance4", label = "Custom Dans 4"},
            {name = "ddance5", label = "Custom Dans 5"},
            {name = "ddance6", label = "Custom Dans 6"},
            {name = "ddance7", label = "Custom Dans 7"},
            {name = "ddance8", label = "Custom Dans 8"},
            {name = "ddance9", label = "Custom Dans 9"},
            {name = "ddance10", label = "Custom Dans 10"},
            {name = "ddance11", label = "Custom Dans 11"},
            {name = "ddance12", label = "Custom Dans 12"},
            {name = "ddance13", label = "Custom Dans 13"},
            {name = "divdance1", label = "Custom Dans 14"},
            {name = "divdance2", label = "Custom Dans 15"},
            {name = "divdance3", label = "Custom Dans 16"},
            {name = "divdance4", label = "Custom Dans 17"},
            {name = "divdance5", label = "Custom Dans 18"},
            {name = "divdance6", label = "Custom Dans 19"},
            {name = "divdance7", label = "Custom Dans 20"},
            {name = "divdance8", label = "Custom Dans 21"},
            {name = "divdance9", label = "Custom Dans 22"},
            {name = "divdance10", label = "Custom Dans 23"},
            {name = "divdance11", label = "Custom Dans 24"},
            {name = "divdance12", label = "Custom Dans 25"},
            {name = "divdance13", label = "Custom Dans 26"},
            {name = "divdance14", label = "Custom Dans 27"},
            {name = "divbdance1", label = "Breakdance 1"},
            {name = "divbdance2", label = "Breakdance 2"},
            {name = "divbdance3", label = "Breakdance 3"},
            {name = "divbdance4", label = "Breakdance 4"},
            {name = "divbdance5", label = "Breakdance 5"},
            {name = "divbdance6", label = "Breakdance 6"},
            {name = "divbdance7", label = "Breakdance 7"},
            {name = "divbdance8", label = "Breakdance 8"},
            {name = "divbdance9", label = "Breakdance 9"},
            {name = "divbdance10", label = "Breakdance 10"},
            {name = "divbdance11", label = "Breakdance 11"},
            {name = "divbdance12", label = "Breakdance 12"},
            {name = "divbdance13", label = "Breakdance 13"},
            {name = "divbdance14", label = "Breakdance 14"},
        }
    },
    {
        label = 'Danse Emotes #4',
        items = {
            {name = "toprock", label = "Toprock"},
            {name = "popdance", label = "Pop Smoke Dance"},
            {name = "catdaddy", label = "Cat Daddy"},
            {name = "blixkytwirl2", label = "Blixky Twirl"},
            {name = "bloodwalk2", label = "Blood Walk"},
            {name = "sturdy2", label = "Get Sturdy"},
            {name = "cripwalk2", label = "Crip Walk"},
            {name = "drilldance", label = "Drill Dance"},
            {name = "woowalk", label = "Woo Walk"},
            {name = "woahdance", label = "Woah"},
            {name = "windmillfloss", label = "Windmill Floss"},
            {name = "showroomdance", label = "Showroom Dance"},
            {name = "mellow", label = "Mellow"},
            {name = "maskoff", label = "Mask Off"},
            {name = "marat", label = "Marat"},
            {name = "magicman", label = "Magic Man"},
            {name = "linedance", label = "Dance Line"},
            {name = "kingdance", label = "The King's Dance"},
            {name = "dabloop", label = "Dab Loop"},
            {name = "hulahula", label = "Hula-Hula"},
            {name = "hotdance", label = "Hot Dance"},
            {name = "squaredance", label = "Square Dance"},
            {name = "hilowave", label = "Hi Lo Wave"},
            {name = "hiphoptaunt", label = "Hip Hop Taunt"},
            {name = "hippiedance", label = "Hippie Dance"},
            {name = "hipsterdance", label = "Hipster Dance"},
            {name = "hiphopdance", label = "Hip Hop Dance"},
            {name = "capoeiramove", label = "Capoeira Move"},
            {name = "bboydance", label = "BBoy Dance"},
            {name = "bopdance", label = "Bop"},
            {name = "banddance", label = "Band Dance"},
            {name = "ashton", label = "Ashton"},
            {name = "charleston", label = "Charleston"},
            {name = "doggystrut", label = "Doggy Strut"},
            {name = "dreamfeet", label = "Dream feat"},
            {name = "eerie", label = "Eerie"},
            {name = "fancyfeet", label = "Fancy Feet"},
            {name = "festivus", label = "Festivus"},
            {name = "flamingo", label = "Flamingo"},
            {name = "fresh", label = "Fresh"},
            {name = "getgriddy", label = "Get Griddy"},
            {name = "handstand", label = "Handstand"},
            {name = "keepdance", label = "Goof Off"},
            {name = "imsmooth", label = "Smooth"},
            {name = "montecarlo", label = "Monte Carlo"},
            {name = "octopus", label = "Octopus"},
            {name = "pointydance", label = "Pointy"},
            {name = "ridingdance", label = "Riding Cowboy"},
            {name = "skeldance", label = "Skeleton Dance"},
            {name = "spinny", label = "Spinny"},
            {name = "zombiewalk", label = "Zombie Walk"},
            {name = "woowalkinx", label = "Woo Walk"},
            {name = "bloodwalk", label = "Blood Walk"},
            {name = "cripwalk3", label = "Crip Walk"},
            {name = "shootit", label = "Shoot Dance"},
            {name = "millyrocks", label = "Milly Rock"},
            {name = "shmoney", label = "Shmoney Dance"},
            {name = "dougie", label = "Dougie"},
            {name = "haiphuthon", label = "Haiphuthon"},
            {name = "curvette", label = "Curvette"},
            {name = "tokyochall", label = "Tokyo Challenge"},
            {name = "thotiana", label = "Thotiana"},
            {name = "moodswings", label = "Moodswings Dance"},
            {name = "whatyouknowboutlove", label = "Pop Love"},
        }
    },
    {
        label = 'DJ Dance Emotes',
        items = {
            {label = "DJ Dance 1", name = "djdance1"},
            {label = "DJ Dance 2", name = "djdance2"},
            {label = "DJ Dance 3", name = "djdance3"},
            {label = "DJ Dance 4", name = "djdance4"},
            {label = "DJ Dance 5", name = "djdance5"},
            {label = "DJ Dance 6", name = "djdance6"},
            {label = "DJ Dance 7", name = "djdance7"},
            {label = "DJ Dance 8", name = "djdance8"},
            {label = "DJ Dance 9", name = "djdance9"},
            {label = "DJ Dance 10", name = "djdance10"},
            {label = "DJ Dance 11", name = "djdance11"},
            {label = "DJ Dance 12", name = "djdance12"},
            {label = "DJ Dance 13", name = "djdance13"},
            {label = "DJ Dance 14", name = "djdance14"},
            {label = "DJ Dance 15", name = "djdance15"},
            {label = "DJ Dance 16", name = "djdance16"},
            {label = "DJ Dance 17", name = "djdance17"},
            {label = "DJ Dance 18", name = "djdance18"},
            {label = "DJ Dance 19", name = "djdance19"},
            {label = "DJ Dance 20", name = "djdance20"},
            {label = "DJ Dance 21", name = "djdance21"},
            {label = "DJ Dance 22", name = "djdance22"},
            {label = "DJ Dance 23", name = "djdance23"},
            {label = "DJ Dance 24", name = "djdance24"},
            {label = "DJ Dance 25", name = "djdance25"},
            {label = "DJ Dance 26", name = "djdance26"},
            {label = "DJ Dance 27", name = "djdance27"},
            {label = "DJ Dance 28", name = "djdance28"},
            {label = "DJ Dance 29", name = "djdance29"},
            {label = "DJ Dance 30", name = "djdance30"}
        }
    },
    {
        label = 'DJ Dance Idles',
        items = {
            {label = "DJ Dance 8", name = "djidle1"},
            {label = "DJ Dance 9", name = "djidle2"},
            {label = "DJ Dance 10", name = "djidle3"},
            {label = "DJ Dance 11", name = "djidle4"},
            {label = "DJ Dance 12", name = "djidle5"},
            {label = "DJ Dance 13", name = "djidle6"},
            {label = "DJ Dance 14", name = "djidle7"},
            {label = "DJ Dance 15", name = "djidle8"},
            {label = "DJ Dance 16", name = "djidle9"},
            {label = "DJ Dance 17", name = "djidle10"},
            {label = "DJ Dance 18", name = "djidle11"},
            {label = "DJ Dance 19", name = "djidle12"},
            {label = "DJ Dance 20", name = "djidle13"},
            {label = "DJ Dance 21", name = "djidle14"},
            {label = "DJ Dance 22", name = "djidle15"},
            {label = "DJ Dance 23", name = "djidle16"},
            {label = "DJ Dance 24", name = "djidle17"},
            {label = "DJ Dance 25", name = "djidle18"},
            {label = "DJ Dance 26", name = "djidle19"},
            {label = "DJ Dance 27", name = "djidle20"},
            {label = "DJ Dance 28", name = "djidle21"},
            {label = "DJ Dance 29", name = "djidle22"},
            {label = "DJ Dance 30", name = "djidle23"},
            {label = "DJ Dance 31", name = "djidle24"},
            {label = "DJ Dance 32", name = "djidle25"},
            {label = "DJ Dance 33", name = "djidle26"},
            {label = "DJ Dance 34", name = "djidle27"},
            {label = "DJ Dance 35", name = "djidle28"},
            {label = "DJ Dance 36", name = "djidle29"},
            {label = "DJ Dance 37", name = "djidle30"},
            {label = "DJ Dance 38", name = "djidle31"},
            {label = "DJ Dance 39", name = "djidle32"},
            {label = "DJ Dance 40", name = "djidle33"},
            {label = "DJ Dance 41", name = "djidle34"},
            {label = "DJ Dance 42", name = "djidle35"},
            {label = "DJ Dance 43", name = "djidle36"},
            {label = "DJ Dance 44", name = "djidle37"},
            {label = "DJ Dance 45", name = "djidle38"},
            {label = "DJ Dance 46", name = "djidle39"},
            {label = "DJ Dance 47", name = "djidle40"},
            {label = "DJ Dance 48", name = "djidle41"},
            {label = "DJ Dance 49", name = "djidle42"},
            {label = "DJ Dance 50", name = "djidle43"},
            {label = "DJ Dance 51", name = "djidle44"},
            {label = "DJ Dance 52", name = "djidle45"},
            {label = "DJ Dance 53", name = "djidle46"},
            {label = "DJ Dance 54", name = "djidle47"},
            {label = "DJ Dance 55", name = "djidle48"},
            {label = "DJ Dance 56", name = "djidle49"},
            {label = "DJ Dance 57", name = "djidle50"},
            {label = "DJ Dance 58", name = "djidle51"},
            {label = "DJ Dance 59", name = "djidle52"},
            {label = "DJ Dance 60", name = "djidle53"}
        }
    },
    {
        label = '18+ Animationer',
        items = {
            {label = "Pos 1", name = "kneesass"},
            {label = "Pos 2", name = "kneesassm"},
            {label = "Pos 3", name = "sidegrab"},
            {label = "Pos 4", name = "sidegrabf"},
            {label = "Pos 5", name = "sidemissionary"},
            {label = "Pos 6", name = "sidemissionarym"},
            {label = "Pos 7", name = "sidewaysm"},
            {label = "Pos 8", name = "sidewaysf"},
            {label = "Pos 9", name = "topside"},
            {label = "Pos 10", name = "topsidef"},
            {label = "Pos 11", name = "topside2"},
            {label = "Pos 12", name = "topside2f"},
            {label = "Pos 13", name = "seex1"},
            {label = "Pos 14", name = "seex2"},
            {label = "Pos 15", name = "seex3"},
            {label = "Pos 16", name = "seex4"},
            {label = "Pos 17", name = "seex5"},
            {label = "Pos 18", name = "seex6"},
        }
    },
    {
        label = 'Billede poseringer',
        items = {
            {label = "Kvinde Pose 1", name = "pose1"},
            {label = "Kvinde Pose 2", name = "pose2"},
            {label = "Kvinde Pose 3", name = "pose3"},
            {label = "Kvinde Pose 4", name = "pose4"},
            {label = "Kvinde Pose 5", name = "pose5"},
            {label = "Kvinde Pose 6", name = "pose6"},
            {label = "Kvinde Pose 7", name = "pose7"},
            {label = "Kvinde Pose 8", name = "pose8"},
            {label = "Kvinde Pose 9", name = "pose9"},
            {label = "Kvinde Pose 10", name = "pose10"},
            {label = "Kvinde Pose 11", name = "pose11"},
            {label = "Kvinde Pose 12", name = "pose12"},
            {label = "Kvinde Pose 13", name = "pose13"},
            {label = "Kvinde Pose 14", name = "pose14"},
            {label = "Kvinde Pose 15", name = "pose15"},
            {label = "Kvinde Pose 16", name = "pose16"},
            {label = "Kvinde Pose 17", name = "pose17"},
            {label = "Kvinde Pose 18", name = "pose18"},
            {label = "Kvinde Pose 19", name = "pose19"},
            {label = "Kvinde Pose 20", name = "pose20"},
            {label = "Mande Pose 1", name = "malepose1"},
            {label = "Mande Pose 2", name = "malepose2"},
            {label = "Mande Pose 3", name = "malepose3"},
            {label = "Mande Pose 4", name = "malepose4"},
            {label = "Mande Pose 5", name = "malepose5"},
            {label = "Mande Pose 6", name = "malepose6"},
            {label = "Mande Pose 7", name = "malepose7"},
            {label = "Mande Pose 8", name = "malepose8"},
        }
    },
}

Config.CarAnimations = {
    {
        label = 'Festlige',
        items = {
            {label = "Kast op", name = 'vehtrhow'},
        }
    },
    {
        label = 'Arbejde',
        items = {
            {label = "Taxa: Ledig", name = 'vehtaxi1'},
            {label = "Taxa: giv regning", name = 'vehtaxi2'},
        }
    },
    {
        label = 'Seksuelle',
        items = {
            {label = "Bil: Blowjob M", name = 'vehblowm'},
            {label = "Bil: Blowjob K", name = 'vehblowf'},
            {label = "Bil: Sex M", name = 'vehsexm'},
            {label = "Bil: Sex K", name = 'vehsexf'},
        }
    }
}

Config.VehicleMenu = {
    {label = "Åbn/Luk Kølerhjelm", value = 'open_hood'},
    {label = "Åbn/Luk Bagagerum", value = 'open_trunk'},
    {label = "Åbn/Luk Alt", value = 'open_all'},
    {label = "Tænd/Sluk Neonlys", value = 'neon_control'},
    {label = "Tænd/Sluk Motor", value = 'engine_toggle'},
}

Config.QuickCommands = {
    {label = "Mit Telefon Nummer", value = 'show_phonenumber'},
    {label = "Blindfold af/på", value = 'blindfold_toggle'},
    {label = "ID Kort", value = 'show_id'},
    {label = "Overgiv Dig", value = 'surrender_now'},
}

Config.PersonalCommands = {
    {label = "Hat af/på", value = 'hat_toggle'},
    {label = "Briller af/på", value = 'glasses_toggle'},
    {label = "Maske af/på", value = 'mask_toggle'},
    {label = "Taske af/på", value = 'bag_toggle'},
    {label = "Trøje af/på", value = 'shirt_toggle'},
    {label = "Bukser af/på", value = 'pants_toggle'},
    {label = "Sko af/på", value = 'shoes_toggle'},
    {label = "Ur af/på", value = 'watch_toggle'},
    {label = "Halskæde af/på", value = 'chain_toggle'},
    {label = "Skudsikkervest af/på", value = 'vest_toggle'},
    {label = "Mærker af/på", value = 'decals_toggle'},
}

Config.CrimeMenu = {
    {label = "Giv Strips på", value = 'ziptie_on'},
    {label = "Tag Strips af", value = 'ziptie_off'},
    {label = "Sæt i køretøj", value = 'put_vehicle'},
    {label = "Fjern fra køretøj", value = 'takeout_vehicle'},
    {label = "Tjek lommer", value = 'check_pockets'},
    {label = "Eskorter", value = 'drag_person'},
}
